---
apiVersion: v1
kind: Template
labels:
  template: hello
metadata:
  annotations:
    description: This is an example of application template in OpenShift 3
    iconClass: default
    tags: hello, world
  name: hello-world-template
  namespace: $(namespace)
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      name: hello-world-service
    spec:
      ports:
        - name: http
          nodePort: 0
          port: ${{SERVICE_PORT}}
          protocol: TCP
          targetPort: ${{INTERNAL_PORT}}
      selector:
        name: hello
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        name: hello
      name: hello-world-route
    spec:
      host: ${APPLICATION_DOMAIN}
      tls:
        termination: edge
      to:
        kind: Service
        name: hello-world-service
  - apiVersion: v1
    kind: ReplicationController
    metadata:
      name: hello-world-rc
    spec:
      replicas: 1
      selector:
        name: hello
      template:
        metadata:
          creationTimestamp: null
          labels:
            name: hello
        spec:
          containers:
            - env:
                - name: MESSAGE
                  value: ${GREATING_MESSAGE}
              image: docker.io/kalise/nodejs-web-app:latest
              imagePullPolicy: IfNotPresent
              name: hello
              ports:
                - containerPort: ${{INTERNAL_PORT}}
                  name: http
                  protocol: TCP
              resources:
                limits:
                  cpu: 25m
                  memory: 128Mi
              securityContext:
                privileged: false
              livenessProbe:
                tcpSocket:
                  port: ${{INTERNAL_PORT}}
                timeoutSeconds: 1
                initialDelaySeconds: 30
              terminationMessagePath: /dev/termination-log
          dnsPolicy: ClusterFirst
          nodeSelector:
            region: primary
          restartPolicy: Always
          serviceAccount: ""
parameters:
  - description: The exposed hostname that will route to the Hello World service
    name: APPLICATION_DOMAIN
    value: "hello-world.cloud.openshift.b-cloud.it"
    required: true
  - description: The internal port used by the pods
    name: INTERNAL_PORT
    value: "8080"
    required: true
  - description: The port exposed by the service
    name: SERVICE_PORT
    value: "9000"
    required: true
  - description: Greating message
    name: GREATING_MESSAGE
    value: "Hello OpenShift"